### ISSUE TITLE
Doesn't seem to work with LocalTuya lights

### ISSUE THREAD

**Issue by zkvvoob** [chazzu/hass-animated-scenes#16]
Hello,

I've installed and configured the Animated Scenes custom component. Below is my config. The two lights are using the LocalTuya integration. The Animated Scenes switch does turn the lights on, but doesn't seem to be passing the colour values to them - the only thing the lights do is go through the colours set in the Tuya Smart Life app.

```yaml
switch:
  - platform: animated_scenes
    name: Neon
    restore: False 
    ignore_off: False
    restore_power: True
    lights:
      - light.desk_left_light
      - light.desk_right_light
    brightness: [100, 255]
    colors:
      - color_type: rgb_color
        color: [ 253, 197, 245 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 247, 174, 248 ]
        one_change_per_tick: True
        weight: 5
      - color_type: rgb_color
        color: [ 179, 136, 235 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 128, 147, 241 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 114, 221, 247 ]
        one_change_per_tick: True
    transition: [1, 5]
    change_frequency: 5
    change_amount: 6
```

Is there anything I could do to help you figure out what's wrong?

Thanks!
