### ISSUE TITLE
"Quick reload" spikes HA container CPU usage to 100% and requires container restart

### ISSUE THREAD

**Issue by finder39** [chazzu/hass-animated-scenes#21]
So if you create/modify an animated scene and use the "Quick reload" to create/update it the container CPU use goes to 100% and it stays there. It doesn't allow toggling of the switch anymore. It kinda freezes it as a whole.

If you "Restart Home Assistant" it fixes it and things work as intended. I wonder if theres some kind of leak for it in quick reloading the YAML of configurations without restart.

Let me know if theres anything I can do to help debug this.

Heres the scene I created:
```yaml
- platform: animated_scenes
  name: Tokyo
  lights:
  - light.hue_color_candle_1
  - light.hue_color_candle_2
  - light.hue_color_candle_3
  - light.family_room_lamp_colored_hue
  - light.kitchen_divider_hue_1
  - light.kitchen_divider_hue_2
  - light.kitchen_overhead_hue_1
  - light.kitchen_overhead_hue_2
  - light.kitchen_overhead_hue_3
  - light.kitchen_overhead_hue_4
  - light.kitchen_overhead_hue_5
  - light.dining_room_lightstrip_plus
  - light.dining_room_overhead_hue_1
  - light.dining_room_overhead_hue_2
  - light.garage_entry_hue_1
  - light.garage_entry_hue_2

  # https://convertingcolors.com/
  colors:
  - color_type: rgb_color
    color: [ 255, 43, 120 ] # red
    brightness: 140
    nearby_colors: 3
  - color_type: rgb_color
    color: [ 169, 25, 255 ] # purple
    brightness: 140
    weight: 6
    nearby_colors: 3
  - color_type: rgb_color
    color: [ 61, 144, 255 ] # blue
    brightness: 140
    weight: 2
  - color_type: rgb_color
    color: [ 255, 161, 37 ] # orange
    brightness: 140
  - color_type: rgb_color
    color: [ 92, 8, 255 ] # deep blue
    brightness: 140
    weight: 4
    
  transition: [2, 4]
  change_frequency: [5,10]
  change_amount: 2
```
