### ISSUE TITLE
Feature req: Would be nice to animate multiple bulbs as a group (all lights turn same color)

### ISSUE THREAD

**Issue by kupietools** [chazzu/hass-animated-scenes#3]
Currently, if I set it to change a certain group of bulbs, they all turn different colors. It would be nice to be able to set it to change a number of bulbs in unison, all to the same random color together every time they change.

**Comment by MaksimPuzyrkov** [comment]
You can set group of lights and add group to animated scene. So all lights in group will change to same color.

Here's example from my setup:


``` yaml
light:
  - name: Disco Lights
    platform: group
    entities:
      - light.office_up
      - light.office_down
      - light.living_room_window_left
      - light.living_room_window_right

animated_scenes:

switch:
  - platform: animated_scenes
    name: Rainbow
    lights:
      - light.disco_lights
    brightness: 255
    colors:
      - color_type: rgb_color
        color: [ 255, 000, 000 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 255, 165, 000 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 255, 255, 000 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 000, 255, 000 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 000, 000, 255 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 075, 000, 130 ]
        one_change_per_tick: True
      - color_type: rgb_color
        color: [ 238, 130, 238 ]
        one_change_per_tick: True
    transition: [1, 5]
    change_frequency: [5, 10]
    change_amount: all
```
