### ISSUE TITLE
Different colors of several lights in the same scene.

### ISSUE THREAD

**Issue by Smarthome-Creator** [chazzu/hass-animated-scenes#34]
@chazzu, super project and also works great.
One question, is it possible to run several lights of the same scene not synchronized?

**Comment by chazzu** [comment]
What do you mean by not synchronized?

One thing I've settled on doing is setting up an animation as a script. For example:

```yaml
alias: Start Spooky
sequence:
  - service: animated_scenes.start_animation
    data:
      priority: 0
      transition: 2
      change_frequency: 5
      change_amount: all
      ignore_off: true
      restore: true
      restore_power: true
      change_sequence: false
      animate_brightness: true
      animate_color: true
      name: "{{ identifier }}"
      lights: "{{ lights }}"
      colors:
        - color_type: rgb_color
          color:
            - 247
            - 95
            - 28
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 255
            - 154
            - 0
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 136
            - 30
            - 228
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 133
            - 226
            - 31
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 148
            - 0
            - 211
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 200
            - 10
            - 10
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 135
            - 169
            - 107
          one_change_per_tick: true
          nearby_colors: 5
        - color_type: rgb_color
          color:
            - 103
            - 76
            - 71
          one_change_per_tick: true
          nearby_colors: 5
mode: single
```

Now I have my scene and it accepts two params, `identifier` and `lights` so I can do this:

```
service: script.start_spooky
data:
  identifier: spooky_living_room
  lights:
    - light.living_room_1
    - light.living_room_2
    - light.living_room_3
```

This will start the scene in the living room. And if I want it to do another room at the same time:

```
service: script.start_spooky
data:
  identifier: spooky_kitceh
  lights:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
```

Technically now I'm running the same scene in two places, but they are running independent of one another. Is that what you mean?
